- name: Install RabbitMQ
  hosts: rabbitmq
  become: yes
  tasks:
    - name: Configure RabbitMQ Yum Repositories
      ansible.builtin.shell:
        cmd: "{{ item }}"
      loop:
        - "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
        - "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"
      register: repo_output

    - name: Install RabbitMQ
      ansible.builtin.yum:
        name: rabbitmq-server
        state: present
      when: 
        - repo_output|success

    - name: Restart RabbitMQ
      ansible.builtin.service:
        name: rabbitmq-server
        state: restarted
        enabled: true
      when: 
        - repo_output|success

    - name: Create RabbitMQ User
      ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123
      when: 
        - repo_output|success

    - name: Setup Permissions
      ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
      when: 
        - repo_output|success