- name: Install Redis component
  hosts: redis
  become: yes
  tasks:
  - name: Enable Redis topic
      command: amazon-linux-extras enable redis4.0
  - name: Install Redis
      yum:
        name: redis
        state: present

  - name: Allow remote connections to redis
    ansible.builtin.replace:
      path: /etc/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
    when:
      - ansible.builtin.stat:
          path: /etc/redis.conf
      # If the file exists, then proceed with the replace action

  - name: Start and enable redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes
