- name: Install Redis component
  hosts: redis
  become: yes
  tasks:
  - name: Install Redis repo
      amazon.linux.yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: present
        disable_gpg_check: true

  - name: Enable redis 6.2
    ansible.builtin.command: amazon-linux-extras enable redis6.2
      become: true

  - name: Install redis
    ansible.builtin.yum:
      name: redis
      state: installed
  
  - name: Allow remote connections to redis
    ansible.builtin.replace:
      path: /etc/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: start and enable redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes