- name: Install Redis component
  hosts: redis
  become: yes
  tasks:
  - name: Enable Redis topic
    command: amazon-linux-extras enable redis4.0
  - name: Install Redis
    yum:
      name: redis
      state: present

  - name: Allow remote connections to redis
    ansible.builtin.replace:
      path: /etc/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
    when: ansible.builtin.file:
      path: /etc/redis.conf
      state: file
      exists: true

  - name: Start and enable redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes
